/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const zylith_wallet_build_cancel_request: (a: number, b: number) => [number, number, number, number];
export const zylith_wallet_build_deposit_submission_plan: (a: number, b: number) => [number, number, number, number];
export const zylith_wallet_build_note_membership: (a: number, b: number) => [number, number, number, number];
export const zylith_wallet_build_order_request: (a: number, b: number) => [number, number, number, number];
export const zylith_wallet_build_residual_recovery: (a: number, b: number) => [number, number, number, number];
export const zylith_wallet_build_status_requests: (a: number, b: number) => [number, number, number, number];
export const zylith_wallet_build_withdraw_request: (a: number, b: number) => [number, number, number, number];
export const zylith_wallet_create_recovery_snapshot: (a: number, b: number) => [number, number, number, number];
export const zylith_wallet_decrypt_recovery_artifact: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const zylith_wallet_derive_public_config: (a: number, b: number) => [number, number, number, number];
export const zylith_wallet_generate_seed_hex: () => [number, number];
export const zylith_wallet_market_ids: (a: number, b: number) => [number, number, number, number];
export const zylith_wallet_note_summary: (a: number, b: number) => [number, number, number, number];
export const zylith_wallet_quote_residual_recovery: (a: number, b: number) => [number, number, number, number];
export const zylith_wallet_recover_order_outputs: (a: number, b: number) => [number, number, number, number];
export const zylith_wallet_recover_order_residuals: (a: number, b: number) => [number, number, number, number];
export const zylith_wallet_recovery_auth_tag: (a: number, b: number) => [number, number, number, number];
export const zylith_wallet_registry_fingerprint: (a: number, b: number) => [number, number, number, number];
export const zylith_wallet_sign_strk20_exit_claim: (a: number, b: number) => [number, number, number, number];
export const zylith_wallet_transition_output_root: (a: number, b: number) => [number, number, number, number];
export const init: () => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
