/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_walletsession_free: (a: number, b: number) => void;
export const walletsession_buildCancelRequest: (a: number, b: number, c: number) => [number, number, number, number];
export const walletsession_buildDepositSubmissionPlan: (a: number, b: number, c: number) => [number, number, number, number];
export const walletsession_buildOrderRequest: (a: number, b: number, c: number) => [number, number, number, number];
export const walletsession_buildResidualRecovery: (a: number, b: number, c: number) => [number, number, number, number];
export const walletsession_buildStatusRequests: (a: number, b: number, c: number) => [number, number, number, number];
export const walletsession_buildWithdrawRequest: (a: number, b: number, c: number) => [number, number, number, number];
export const walletsession_createRecoverySnapshot: (a: number, b: number, c: number) => [number, number, number, number];
export const walletsession_decryptLocalState: (a: number, b: number, c: number) => [number, number, number, number];
export const walletsession_decryptLocalStateClassified: (a: number, b: number, c: number) => [number, number, number, number];
export const walletsession_decryptRecoveryArtifact: (a: number, b: number, c: number) => [number, number, number, number];
export const walletsession_decryptRecoveryArtifactClassified: (a: number, b: number, c: number) => [number, number, number, number];
export const walletsession_deriveProofSigner: (a: number, b: number, c: number) => [number, number, number, number];
export const walletsession_encryptLocalState: (a: number, b: number, c: number) => [number, number, number, number];
export const walletsession_isLocked: (a: number) => number;
export const walletsession_lock: (a: number) => void;
export const walletsession_new: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number];
export const walletsession_publicConfig: (a: number) => [number, number, number, number];
export const walletsession_recoveryAuthTag: (a: number) => [number, number, number, number];
export const walletsession_signStrk20ExitClaim: (a: number, b: number, c: number) => [number, number, number, number];
export const zylith_wallet_build_note_membership: (a: number, b: number) => [number, number, number, number];
export const zylith_wallet_market_ids: (a: number, b: number) => [number, number, number, number];
export const zylith_wallet_note_summary: (a: number, b: number) => [number, number, number, number];
export const zylith_wallet_quote_residual_recovery: (a: number, b: number) => [number, number, number, number];
export const zylith_wallet_recover_order_outputs: (a: number, b: number) => [number, number, number, number];
export const zylith_wallet_recover_order_residuals: (a: number, b: number) => [number, number, number, number];
export const zylith_wallet_registry_fingerprint: (a: number, b: number) => [number, number, number, number];
export const zylith_wallet_transition_output_root: (a: number, b: number) => [number, number, number, number];
export const init: () => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
